# Generated by Django 2.1.7 on 2019-03-10 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='first',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='first',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
